### ISSUE TITLE
Problems starting SSU

### ISSUE THREAD

**Issue by bjoseph** [wesabe/ssu#11]
I followed the directions in the README. It looks like the server starts, albeit with a few errors: 

http://screencast.com/t/zMa0VJQfpoUM

However, when I try to start the console, it just hangs:

http://screencast.com/t/5wgv6yWavm

It seems to hang on this line in the "run" method in script/console: require File.expand_path('../console.rb', **FILE**)

I thought maybe it because I was running an old version of Ruby but I still see the issue with Ruby 1.9.3.

Any thoughts? I have tried everything I can think of.

Thanks!

**Comment by sirish-sj** [comment]
I too have the same issue. Tried on multiple machines (both Macs) and noticed similar behavior. I would appreciate any suggestions to fix this issue.

**Comment by bjoseph** [comment]
Seems to be working now with the latest download.  Thanks!
