### ISSUE TITLE
Paypal does not work OOTB

### ISSUE THREAD

**Issue by threeseed** [wesabe/ssu#3]
Out of the box, SSU does not work with Paypal and potentially other sources.
1. Install SSU on either Linux or Mac using provided install instructions
2. Generate valid credentials.
3. Connect to server via local console and start job.
4. It successfully logs in, navigates to the download and begins the download. 
5. It hangs until the whole job times out.

**Comment by eventualbuddha** [comment]
@taligent: mind pasting some of the logs in here? Please make sure to scrub any sensitive info before doing so. Thanks!
