### ISSUE TITLE
Could not find templater (>= 0.3.2)  Error when generating credentials

### ISSUE THREAD

**Issue by ghost** [wesabe/ssu#4]
I downloaded the wesabe ssu yesterday and have been stuck at the following.  I am using this on Mac OSX 10.6.8 and Ruby Version is 1.8.7. 

Do i have to downgrade to version 1.3.6?  

If not, please advise on the steps. 

Thank you in advance for you help.

NCS

script/generate credential com.chase chase
/Library/Ruby/Site/1.8/rubygems/dependency.rb:247:in `to_specs': Could not find templater (>= 0.3.2) amongst [RedCloth-4.1.1, actionmailer-2.3.5, actionmailer-1.3.6, actionpack-2.3.5, actionpack-1.13.6, actionwebservice-1.2.6, activerecord-2.3.5, activerecord-1.15.6, activeresource-2.3.5, activesupport-2.3.5, activesupport-1.4.4, acts_as_ferret-0.4.3, capistrano-2.5.2, cgi_multipart_eof_fix-2.5.0, daemons-1.0.10, dnssd-0.6.0, fastthread-1.0.1, fcgi-0.8.7, ferret-0.11.6, gem_plugin-0.2.3, highline-1.5.0, hpricot-0.6.164, libxml-ruby-1.1.2, mongrel-1.1.5, needle-1.3.0, net-scp-1.0.1, net-sftp-2.0.1, net-sftp-1.1.1, net-ssh-2.0.4, net-ssh-1.1.4, net-ssh-gateway-1.0.0, rack-1.0.1, rails-2.3.5, rails-1.2.6, rake-0.9.2, rake-0.9.2, rake-0.8.3, rdoc-3.9.4, rdoc-3.9.4, ruby-openid-2.1.2, ruby-yadis-0.3.4, rubygems-update-1.8.10, rubynode-0.1.5, sqlite3-ruby-1.2.4, termios-0.9.4, xmpp4r-0.4] (Gem::LoadError)
    from /Library/Ruby/Site/1.8/rubygems/dependency.rb:256:in`to_spec'
    from /Library/Ruby/Site/1.8/rubygems.rb:1210:in `gem'
    from script/generate:4

**Comment by eventualbuddha** [comment]
I recommend trying the `commonjs` branch. That uses bundler, so you can simply run `bundle install` before running the generate script. Please reopen this if you still have issues.
